--------------------------------------------------------------------------------------
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE MEMBER_ADD CASCADE CONSTRAINTS;

DROP TABLE CATEGORY CASCADE CONSTRAINTS;

DROP TABLE RECR_BOARD CASCADE CONSTRAINTS;
DROP TABLE RECR_APPL CASCADE CONSTRAINTS;

DROP TABLE COMM_RECR CASCADE CONSTRAINTS;
DROP TABLE FREE_BOARD CASCADE CONSTRAINTS;
DROP TABLE COMM_FREE CASCADE CONSTRAINTS;

DROP TABLE COMM_QNA CASCADE CONSTRAINTS;
DROP TABLE NOTICE_BOARD CASCADE CONSTRAINTS;
DROP TABLE QNA_BOARD CASCADE CONSTRAINTS;

DROP TABLE FORBIDDEN CASCADE CONSTRAINTS;
DROP TABLE ALARM CASCADE CONSTRAINTS;
drop sequence seq_alarm;
drop trigger trigger_comm_recr;
drop trigger trigger_comm_free;
drop trigger trigger_recr_appl;
drop procedure insert_sample_members;

DROP trigger daily_match_delete_trigger;
DROP Trigger insert_member_add_trigger;
DROP Trigger update_grade_trigger;

--                  MEMBER테이블 -------------------------------------
--                  MEMBER테이블 -------------------------------------
CREATE TABLE MEMBER(

MEMBER_ID	    VARCHAR2(50)    CONSTRAINT PK_MEMBER_ID PRIMARY KEY ,
MEMBER_PWD	    VARCHAR2(100)    NOT NULL,
MEMBER_NICNAME      VARCHAR2(30)   NOT NULL  UNIQUE,
MEMBER_NAME	    VARCHAR2(40)    NOT NULL,
BIRTH	    DATE   NOT NULL ,
GENDER	CHAR(1)	NOT NULL, 
EMAIL	    VARCHAR2(50)    NOT NULL,
ADDRESS    VARCHAR2(200)   NOT NULL,
PICTURE_FILE	    VARCHAR2(100),
RESIGN  	DATE,
ADMIN_YN	    CHAR(1) DEFAULT 'N'     NOT NULL,
SIGNTYPE     VARCHAR2(12)     NOT NULL,
ACT_LIMIT	CHAR(1)    DEFAULT '0'   NOT NULL,
REGIST_DATE	    DATE   DEFAULT SYSDATE     NOT NULL,
MODIFIED_DATE	    DATE   DEFAULT  SYSDATE
);
--MEMBER 코멘트
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '회원패스워드';
COMMENT ON COLUMN MEMBER.MEMBER_NICNAME IS '회원 닉네임';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.BIRTH IS '생일';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.PICTURE_FILE IS '회원사진파일명';
COMMENT ON COLUMN MEMBER.RESIGN IS '회원탈퇴';
COMMENT ON COLUMN MEMBER.ADMIN_YN IS '관리자여부';
COMMENT ON COLUMN MEMBER.SIGNTYPE IS '로그인 종류 : direct/kakao/naver/google';
COMMENT ON COLUMN MEMBER.ACT_LIMIT IS '사용제약';
COMMENT ON COLUMN MEMBER.REGIST_DATE IS '등록일자 ';
COMMENT ON COLUMN MEMBER.MODIFIED_DATE IS '최종수정일자';



--SIGNTYPE   일반->direct, 네이버-> naver, 카카오-> kakao
--RESIGN    일잔-> NULL  ,  회원탈퇴 시 ->현재날짜 + 30




--  MEM_ADD 테이블 -----------------------------------------------

CREATE TABLE MEMBER_ADD(
MEMBER_ID	VARCHAR2(50) CONSTRAINT PK_MEMBER_ADD_ID PRIMARY KEY ,
HEART_BEAT	NUMBER           DEFAULT 30    NOT NULL,
GRADE	    VARCHAR2(10)              DEFAULT '새싹'         NOT NULL,
ARTICLE_COUNT	NUMBER      DEFAULT 0        NOT NULL,
REPORT_COUNT	NUMBER      DEFAULT 0       NOT NULL,
CONSTRAINT FK1 FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE
);




COMMENT ON COLUMN MEMBER_ADD.MEMBER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER_ADD.HEART_BEAT IS '하트비트';
COMMENT ON COLUMN MEMBER_ADD.GRADE IS '등급';
COMMENT ON COLUMN MEMBER_ADD.ARTICLE_COUNT IS '활동건수';
COMMENT ON COLUMN MEMBER_ADD.REPORT_COUNT IS '신고건수';


--MEMBER테이블이 INSERT될때 MEMBER_ADD테이블에도 INSERT되는 트리거
CREATE OR REPLACE TRIGGER insert_member_add_trigger
AFTER INSERT ON MEMBER
FOR EACH ROW
BEGIN
    INSERT INTO MEMBER_ADD (MEMBER_ID, HEART_BEAT, GRADE, ARTICLE_COUNT, REPORT_COUNT)
    VALUES (:NEW.MEMBER_ID, 30, '새싹', 0, 0);
END;
/


--회원탈퇴컬럼과 오늘날짜가 매치되면 해당 회원 삭제됨  >> 30일뒤로 지정
CREATE OR REPLACE TRIGGER daily_match_delete_trigger
AFTER UPDATE OF resign ON member
FOR EACH ROW
DECLARE
    update_resign VARCHAR2(60) := 'daily_match_delete_trigger';
BEGIN
    IF TO_CHAR(SYSDATE, 'HH24:MI' ) = '00:00' THEN
        DBMS_SCHEDULER.CREATE_JOB (
            job_name     => update_resign,
            job_type     =>'PLSQL_BLOCK',
            job_action     =>  'BEGIN
                                        DELETE ON MEMBER
                                        WHERE resign= SYSDATE
                                    END;',
            start_date        =>SYSDATE,
            repeat_interval => 'FREQ=DAILY; BYHOUR=0; BYMINUTE=0',
            enabled         =>TRUE);
    END IF;
END;
/
            
        



--활동 횟수 업데이트 시 횟수에 해당하는 등급도 업데이트 되는 트리거
CREATE OR REPLACE TRIGGER update_grade_trigger
AFTER UPDATE OF ARTICLE_COUNT ON member_add
FOR EACH ROW
BEGIN
    IF :NEW.ARTICLE_COUNT BETWEEN 1 AND 30 THEN
        UPDATE member_add SET GRADE = '새싹' WHERE MEMBER_ID = :NEW.MEMBER_ID;
        
    ELSIF :NEW.ARTICLE_COUNT BETWEEN 31 AND 50 THEN
        UPDATE member_add SET GRADE = '잔디' WHERE MEMBER_ID = :NEW.MEMBER_ID;
        
    ELSIF :NEW.ARTICLE_COUNT BETWEEN 51 AND 70 THEN
        UPDATE member_add SET GRADE = '꽃' WHERE MEMBER_ID = :NEW.MEMBER_ID;
        
    ELSIF :NEW.ARTICLE_COUNT BETWEEN 71 AND 90 THEN
        UPDATE member_add SET GRADE = '나무' WHERE MEMBER_ID = :NEW.MEMBER_ID;
        
    ELSE
        UPDATE member_add SET GRADE = '숲' WHERE MEMBER_ID = :NEW.MEMBER_ID;
    END IF;
END;
/

-- 카테고리 테이블 ----------------------------------------------------


CREATE TABLE C##NORAMOREDB.CATEGORY (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(30),
    ORIGINAL_FILE_NAME VARCHAR2(100),
    RENAME_FILE_NAME VARCHAR2(100),
    REGIST_DATE DATE
);

COMMENT ON COLUMN C##NORAMOREDB.CATEGORY.CATEGORY_ID IS '카테고리 코드';
COMMENT ON COLUMN C##NORAMOREDB.CATEGORY.CATEGORY_NAME IS '카테고리 이름';
COMMENT ON COLUMN C##NORAMOREDB.CATEGORY.ORIGINAL_FILE_NAME IS '원본 파일 이름';
COMMENT ON COLUMN C##NORAMOREDB.CATEGORY.RENAME_FILE_NAME IS '변경 파일 이름';
COMMENT ON COLUMN C##NORAMOREDB.CATEGORY.REGIST_DATE IS '등록일자';

INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, ORIGINAL_FILE_NAME, RENAME_FILE_NAME) VALUES ('1', '볼링', 'categoryImg1', 'categoryImg1.png');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, ORIGINAL_FILE_NAME, RENAME_FILE_NAME) VALUES ('2', '클라이밍', 'categoryImg2', 'categoryImg2.png');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, ORIGINAL_FILE_NAME, RENAME_FILE_NAME) VALUES ('3', '사이클', 'categoryImg3', 'categoryImg3.png');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, ORIGINAL_FILE_NAME, RENAME_FILE_NAME) VALUES ('4', '헬스', 'categoryImg4', 'categoryImg4.png');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, ORIGINAL_FILE_NAME, RENAME_FILE_NAME) VALUES ('5', '수상스포츠', 'categoryImg5', 'categoryImg5.png');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, ORIGINAL_FILE_NAME, RENAME_FILE_NAME) VALUES ('6', '등산', 'categoryImg6', 'categoryImg6.png');

COMMIT;

SELECT * FROM CATEGORY;

---------------------------------------------------------------------------------------


---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
-- 모집 게시판---------------------------------------------------------


-- 모집 게시판---------------------------------------------------------

CREATE TABLE C##NORAMOREDB.RECR_BOARD (
    BOARD_ID NUMBER NOT NULL, -- 모집글 ID
    MEMBER_ID VARCHAR2(50) NOT NULL, -- 모집글 작성자ID
    CATEGORY_ID NUMBER NOT NULL, -- 카테고리ID
    TITLE VARCHAR2(100) NOT NULL, -- 모집글 제목
    CONTEXT VARCHAR2(500) NOT NULL, -- 모집글 내용
    REPORT_COUNT NUMBER DEFAULT 0, -- 신고 횟수
    GENDER_CONDITION CHAR(1), -- 성별 조건
    MIN_AGE_CONDITION NUMBER,  -- 나이조건(최소)
    MAX_AGE_CONDITION NUMBER, -- 나이조건(최대)
    MAX_RECR NUMBER NOT NULL, -- 모집 인원
    NOW_RECR NUMBER DEFAULT 0, -- 현재 인원
    RECR_STATUS VARCHAR(20) DEFAULT '모집중', -- 모집 상태
    RECR_START_DATE DATE DEFAULT SYSDATE, -- 모집시작일
    RECR_END_DATE DATE, -- 모집종료일
    RECR_ORIGINAL_FILENAME VARCHAR2(50), -- 모집원본파일명
    RECR_RENAME_FILENAME VARCHAR2(50), -- 모집변경파일명
    RECR_ACT_START_DATE DATE NOT NULL, -- 활동시작일시
    RECR_ACT_END_DATE DATE NOT NULL, -- 활동종료일시
    RECR_LOC VARCHAR2(100) , -- 위치정보
    COMMENT_COUNT NUMBER DEFAULT 0, -- 댓글 개수
    READ_COUNT NUMBER DEFAULT 0, -- 조회수
    REGIST_DATE DATE DEFAULT SYSDATE, -- 등록일자
    LAST_UPD_DATE DATE DEFAULT SYSDATE, -- 수정일자
    CONSTRAINT RECR_BOARD_PK PRIMARY KEY (BOARD_ID),
    CONSTRAINT FK_RECR_1 FOREIGN KEY (MEMBER_ID) REFERENCES C##NORAMOREDB.MEMBER (MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RECR_2 FOREIGN KEY (CATEGORY_ID) REFERENCES C##NORAMOREDB.CATEGORY (CATEGORY_ID) ON DELETE CASCADE
);

COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.BOARD_ID IS '모집글 ID';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.MEMBER_ID IS '모집글 작성자ID';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.CATEGORY_ID IS '카테고리ID';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.TITLE IS '모집글 제목';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.CONTEXT IS '모집글 내용';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.REPORT_COUNT IS '신고 횟수';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.GENDER_CONDITION IS '성별 조건';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.MIN_AGE_CONDITION IS '나이 조건(최소)';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.MAX_AGE_CONDITION IS '나이 조건(최대)';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.MAX_RECR IS '모집 인원';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.NOW_RECR IS '현재 인원';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.RECR_STATUS IS '모집 상태';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.RECR_START_DATE IS '모집시작일';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.RECR_END_DATE IS '모집종료일';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.RECR_ORIGINAL_FILENAME IS '원본파일명';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.RECR_RENAME_FILENAME IS '변경파일명';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.RECR_ACT_START_DATE IS '활동시작일시';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.RECR_ACT_END_DATE IS '활동종료일시';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.RECR_LOC IS '위치정보';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.COMMENT_COUNT IS '댓글 개수';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.READ_COUNT IS '조회수';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.REGIST_DATE IS '등록일자';
COMMENT ON COLUMN C##NORAMOREDB.RECR_BOARD.LAST_UPD_DATE IS '수정일자';


COMMIT;


---------------------------------------------------------------------------------------


---------------------------------------------------------------------------------------
-- 모집 게시판_모집&신청


CREATE TABLE RECR_APPL (
    BOARD_ID NUMBER PRIMARY KEY, -- 게시글 ID
    MEMBER_ID VARCHAR2(50), -- 회원 ID
    RECR_STATE NUMBER DEFAULT 1, -- 모집 상태 (기본값: 1)
    REGIST_DATE DATE DEFAULT SYSDATE, -- 등록 날짜 (기본값: 현재 시간)
    LAST_UPD_DT DATE DEFAULT SYSDATE, -- 마지막 업데이트 날짜 (기본값: 현재 시간)
    CONSTRAINT FK_RECR_BOARD FOREIGN KEY (BOARD_ID) REFERENCES RECR_BOARD (BOARD_ID) ON DELETE CASCADE,
    CONSTRAINT FK_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE
);

COMMENT ON COLUMN RECR_APPL.BOARD_ID IS '게시글 ID';
COMMENT ON COLUMN RECR_APPL.MEMBER_ID IS '회원 ID';
COMMENT ON COLUMN RECR_APPL.RECR_STATE IS '모집 상태 (기본값: 1)';
COMMENT ON COLUMN RECR_APPL.REGIST_DATE IS '등록 날짜 (기본값: 현재 시간)';
COMMENT ON COLUMN RECR_APPL.LAST_UPD_DT IS '마지막 업데이트 날짜 (기본값: 현재 시간)';

commit;
---------------------------------------------------------------------------------------


---------------------------------------------------------------------------------------
-- 모집 게시판 _ 댓글							




CREATE TABLE COMM_RECR(
    BOARD_ID NUMBER,
    COMMENT_ID NUMBER NOT NULL,
    REF_COMMENT_ID NUMBER,
    MEMBER_ID VARCHAR2(50 BYTE) NOT NULL,
    CONTEXT VARCHAR2(200 BYTE) NOT NULL,
    REPORT_COUNT NUMBER DEFAULT 0,
    COUNT_SUB_COMMENT NUMBER DEFAULT 0,
    REGIST_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT COMMENTS_FK_BOARD_ID FOREIGN KEY (BOARD_ID) REFERENCES RECR_BOARD(BOARD_ID) ON DELETE CASCADE
);
COMMENT ON COLUMN COMM_RECR.BOARD_ID IS '게시판 ID';
COMMENT ON COLUMN COMM_RECR.COMMENT_ID IS '댓글 ID';
COMMENT ON COLUMN COMM_RECR.REF_COMMENT_ID IS '참조 댓글 ID';
COMMENT ON COLUMN COMM_RECR.MEMBER_ID IS '회원 ID';
COMMENT ON COLUMN COMM_RECR.CONTEXT IS '내용';
COMMENT ON COLUMN COMM_RECR.REPORT_COUNT IS '신고 횟수';
COMMENT ON COLUMN COMM_RECR.COUNT_SUB_COMMENT IS '하위댓글 갯수';
COMMENT ON COLUMN COMM_RECR.REGIST_DATE IS '등록 날짜';
COMMENT ON COLUMN COMM_RECR.LAST_UPDATE_DATE IS '최종 수정 날짜';


COMMIT;

-------------------------------------
-- 자유게시판
-------------------------------------



CREATE TABLE C##NORAMOREDB.FREE_BOARD (
    BOARD_ID NUMBER NOT NULL, -- 자유게시판ID
    MEMBER_ID VARCHAR2(50) NOT NULL, -- 자유게시판 작성자
    CATEGORY_ID NUMBER NOT NULL, -- 카테고리 대코드
    TITLE VARCHAR2(50) NOT NULL, -- 자유게시판 제목
    CONTEXT VARCHAR2(200) NOT NULL, -- 자유게시판 내용
    FREE_ORIGINAL_FILENAME VARCHAR2(50), -- 첨부 파일의 원본 이름
    FREE_RENAME_FILENAME VARCHAR2(50), -- 첨부 파일의 변경된 이름
    READ_COUNT NUMBER DEFAULT 0, -- 조회수
    LIKE_COUNT NUMBER DEFAULT 0, -- 좋아요수
    REPORT_COUNT NUMBER DEFAULT 0, -- 신고 횟수
    REGIST_DATE DATE NOT NULL, -- 등록일자
    LAST_UPD_DATE DATE, -- 수정일자
    COMMENT_COUNT NUMBER DEFAULT 0, --댓글개수
    CONSTRAINT FREE_BOARD_PK PRIMARY KEY (BOARD_ID), -- 주요키 설정
    CONSTRAINT FK_FREE_1 FOREIGN KEY (MEMBER_ID) REFERENCES C##NORAMOREDB.MEMBER (MEMBER_ID) ON DELETE CASCADE, -- 외래키 설정
    CONSTRAINT FK_FREE_2 FOREIGN KEY (CATEGORY_ID) REFERENCES C##NORAMOREDB.CATEGORY (CATEGORY_ID) ON DELETE CASCADE -- 외래키 설정
);

COMMENT ON COLUMN C##NORAMOREDB.FREE_BOARD.BOARD_ID IS '자유게시판ID';
COMMENT ON COLUMN C##NORAMOREDB.FREE_BOARD.MEMBER_ID IS '자유게시판 작성자';
COMMENT ON COLUMN C##NORAMOREDB.FREE_BOARD.CATEGORY_ID IS '카테고리 대코드';
COMMENT ON COLUMN C##NORAMOREDB.FREE_BOARD.TITLE IS '자유게시판제목';
COMMENT ON COLUMN C##NORAMOREDB.FREE_BOARD.CONTEXT IS '자유게시판내용';
COMMENT ON COLUMN C##NORAMOREDB.FREE_BOARD.FREE_ORIGINAL_FILENAME IS '첨부 파일의 원본 이름';
COMMENT ON COLUMN C##NORAMOREDB.FREE_BOARD.FREE_RENAME_FILENAME IS '첨부 파일의 변경된 이름';
COMMENT ON COLUMN C##NORAMOREDB.FREE_BOARD.READ_COUNT IS '조회수';
COMMENT ON COLUMN C##NORAMOREDB.FREE_BOARD.LIKE_COUNT IS '좋아요수';
COMMENT ON COLUMN C##NORAMOREDB.FREE_BOARD.REPORT_COUNT IS '신고 횟수';
COMMENT ON COLUMN C##NORAMOREDB.FREE_BOARD.REGIST_DATE IS '등록일자';
COMMENT ON COLUMN C##NORAMOREDB.FREE_BOARD.LAST_UPD_DATE IS '수정일자';
COMMENT ON COLUMN C##NORAMOREDB.FREE_BOARD.COMMENT_COUNT IS '댓글 개수';
                              
                                                                                                  
COMMIT;                                         
                                 
--------------------------------------------------------------------------------------------               
-------------- 자유게시판 댓글
--------------------------------------------------------------------------------------------     
                                          
-- 자유게시판 댓글
CREATE TABLE COMM_FREE(
    BOARD_ID NUMBER,
    COMMENT_ID NUMBER NOT NULL,
    REF_COMMENT_ID NUMBER,
    MEMBER_ID VARCHAR2(50 BYTE) NOT NULL,
    CONTEXT VARCHAR2(200 BYTE) NOT NULL,
    REPORT_COUNT NUMBER DEFAULT 0,
    COUNT_SUB_COMMENT NUMBER DEFAULT 0,
    REGIST_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT COMMENTS_FK_F_BOARD_ID FOREIGN KEY (BOARD_ID) REFERENCES FREE_BOARD(BOARD_ID) ON DELETE CASCADE
);
COMMENT ON COLUMN COMM_FREE.BOARD_ID IS '게시판 ID';
COMMENT ON COLUMN COMM_FREE.COMMENT_ID IS '댓글 ID';
COMMENT ON COLUMN COMM_FREE.REF_COMMENT_ID IS '참조 댓글 ID';
COMMENT ON COLUMN COMM_FREE.MEMBER_ID IS '회원 ID';
COMMENT ON COLUMN COMM_FREE.CONTEXT IS '내용';
COMMENT ON COLUMN COMM_FREE.REPORT_COUNT IS '신고 횟수';
COMMENT ON COLUMN COMM_FREE.COUNT_SUB_COMMENT IS '하위댓글 갯수';
COMMENT ON COLUMN COMM_FREE.REGIST_DATE IS '등록 날짜';
COMMENT ON COLUMN COMM_FREE.LAST_UPDATE_DATE IS '최종 수정 날짜';


COMMIT;
                                             


                                     
                                         
CREATE TABLE C##NORAMOREDB.COMM_QNA                               
   (   BOARD_ID NUMBER NOT NULL ,                            
   COMMENT_NO NUMBER NOT NULL ,                            
   MEMBER_ID VARCHAR2(50) NOT NULL ,                            
   SUBSTANCE VARCHAR2(200) NOT NULL , 
   REF_COMMENT_NO INT DEFAULT 0,                           
   COMMENT_COUNT INT DEFAULT 0,
   REGIST_DT DATE DEFAULT SYSDATE NOT NULL ,                              
   LAST_UPD_DT DATE DEFAULT SYSDATE,                            
   CONSTRAINT COMM_QNA_PK PRIMARY KEY (BOARD_ID, COMMENT_NO) ,            
   CONSTRAINT COMMQ_1 FOREIGN KEY (MEMBER_ID)                           
   REFERENCES C##NORAMOREDB.MEMBER (MEMBER_ID) ON DELETE CASCADE                           
   );                            
                              
   COMMENT ON COLUMN C##NORAMOREDB.COMM_QNA.BOARD_ID IS 'QNA게시판ID';                     
   COMMENT ON COLUMN C##NORAMOREDB.COMM_QNA.COMMENT_NO IS '댓글번호';                     
   COMMENT ON COLUMN C##NORAMOREDB.COMM_QNA.MEMBER_ID IS '댓글 작성자';                     
   COMMENT ON COLUMN C##NORAMOREDB.COMM_QNA.SUBSTANCE IS '댓글 내용';                     
   COMMENT ON COLUMN C##NORAMOREDB.COMM_QNA.REGIST_DT IS '등록일자';                        
   COMMENT ON COLUMN C##NORAMOREDB.COMM_QNA.LAST_UPD_DT IS '최종수정일자';

COMMIT;


CREATE TABLE C##NORAMOREDB.NOTICE_BOARD
(
    BOARD_ID NUMBER NOT NULL ,
    MEMBER_ID VARCHAR2(50) NOT NULL ,
    TITLE VARCHAR2(50) NOT NULL ,
    SUBSTANCE VARCHAR2(200) NOT NULL ,
    READ_COUNT NUMBER,
    REGIST_DT DATE DEFAULT SYSDATE NOT NULL ,
    LAST_UPD_DT DATE DEFAULT SYSDATE,
    ORIGINAL_FILENAME VARCHAR2(50), 
    RENAME_FILENAME VARCHAR2(50),       
    CONSTRAINT NOTICE_BOARD_PK PRIMARY KEY (BOARD_ID) ,
    CONSTRAINT NOTIB_1 FOREIGN KEY (MEMBER_ID) REFERENCES C##NORAMOREDB.MEMBER (MEMBER_ID) ON DELETE CASCADE
); 
COMMENT ON COLUMN C##NORAMOREDB.NOTICE_BOARD.BOARD_ID IS '공지게시판ID';
COMMENT ON COLUMN C##NORAMOREDB.NOTICE_BOARD.MEMBER_ID IS '공지작성자';
COMMENT ON COLUMN C##NORAMOREDB.NOTICE_BOARD.TITLE IS '공지사항 제목';
COMMENT ON COLUMN C##NORAMOREDB.NOTICE_BOARD.SUBSTANCE IS '공지사항 내용';
COMMENT ON COLUMN C##NORAMOREDB.NOTICE_BOARD.READ_COUNT IS '조회수';
COMMENT ON COLUMN C##NORAMOREDB.NOTICE_BOARD.REGIST_DT IS '등록일자';
COMMENT ON COLUMN C##NORAMOREDB.NOTICE_BOARD.LAST_UPD_DT IS '최종수정일자';

COMMIT;

  CREATE TABLE "C##NORAMOREDB"."QNA_BOARD"                      
   (   BOARD_ID NUMBER NOT NULL ENABLE,
   MEMBER_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
   TITLE VARCHAR2(50 BYTE) NOT NULL ENABLE,                   
   SUBSTANCE VARCHAR2(200 BYTE) NOT NULL ENABLE,                   
   READ_COUNT NUMBER DEFAULT 0,                   
   REPORT_COUNT NUMBER DEFAULT 0,                   
   REGIST_DT DATE DEFAULT SYSDATE NOT NULL ENABLE,                   
   LAST_UPD_DT DATE, 
   COMMENT_COUNT INT DEFAULT 0,
   ORIGINAL_FILENAME VARCHAR2(50), 
   RENAME_FILENAME VARCHAR2(50),       
   CONSTRAINT "QNA_BOARD_PK" PRIMARY KEY ("BOARD_ID") ,      
   CONSTRAINT "QNAB_1" FOREIGN KEY ("MEMBER_ID")                  
   REFERENCES "C##NORAMOREDB"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE                  
   );                   
                     
   COMMENT ON COLUMN "C##NORAMOREDB"."QNA_BOARD"."BOARD_ID" IS '질문게시판ID';                     
   COMMENT ON COLUMN "C##NORAMOREDB"."QNA_BOARD"."MEMBER_ID" IS '질문작성자';                     
   COMMENT ON COLUMN "C##NORAMOREDB"."QNA_BOARD"."TITLE" IS '질문제목';                     
   COMMENT ON COLUMN "C##NORAMOREDB"."QNA_BOARD"."SUBSTANCE" IS '질문내용';                     
   COMMENT ON COLUMN "C##NORAMOREDB"."QNA_BOARD"."READ_COUNT" IS '조회수';                     
   COMMENT ON COLUMN "C##NORAMOREDB"."QNA_BOARD"."REPORT_COUNT" IS '신고 횟수';                     
   COMMENT ON COLUMN "C##NORAMOREDB"."QNA_BOARD"."REGIST_DT" IS '등록일자';                     
   COMMENT ON COLUMN "C##NORAMOREDB"."QNA_BOARD"."LAST_UPD_DT" IS '최종수정일자';
 

CREATE TABLE FORBIDDEN (
    FB_ID NUMBER PRIMARY KEY,
    FB_WORD VARCHAR(30) NOT NULL,
    REGIST_DATE DATE NOT NULL
);

COMMENT ON COLUMN C##NORAMOREDB.FORBIDDEN.FB_ID IS '금지어ID';
COMMENT ON COLUMN C##NORAMOREDB.FORBIDDEN.FB_WORD IS '금지어';
COMMENT ON COLUMN C##NORAMOREDB.FORBIDDEN.REGIST_DATE IS '등록일자';

DECLARE
    v_word NVARCHAR2(100);
BEGIN
    FOR i IN 1..211 LOOP
        v_word := DBMS_RANDOM.STRING('A', 5);
        INSERT INTO FORBIDDEN (FB_ID, FB_WORD, REGIST_DATE)
        VALUES (i, v_word, SYSDATE);
    END LOOP;
    COMMIT;
END;
/



Drop table message cascade constraints;

-- MESSAGE 테이블 생성
CREATE TABLE MESSAGE (
   MESSAGE_CONTENT VARCHAR2(300) NOT NULL,
   SENDER VARCHAR2(50) NOT NULL,
   receiver VARCHAR2(50) NOT NULL,
   connect_yn char(5) default 'N',
   regist_date DATE DEFAULT SYSDATE NOT NULL
   --CONSTRAINT FK_SENDER_NO FOREIGN KEY (SENDER_ID) REFERENCES MEMBER(MEMBER_ID)
);

-- MESSAGE 테이블에 주석 추가
COMMENT ON COLUMN MESSAGE.MESSAGE_CONTENT IS '메시지 번호';
COMMENT ON COLUMN MESSAGE.SENDER IS '발신자';
COMMENT ON COLUMN MESSAGE.receiver IS '수신자';
COMMENT ON COLUMN MESSAGE.connect_yn IS '대기 여부';
COMMENT ON COLUMN MESSAGE.regist_date IS '메시지 보낸 시간';


------------------------------------------------------------------

CREATE TABLE ALARM (
    ALARM_ID NUMBER PRIMARY KEY,
    ALARM_KIND CHAR(15) NOT NULL,
    NATIVE_ID VARCHAR(20) NOT NULL,
    RECEIVER_ID VARCHAR(50) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
    SENDER_ID VARCHAR(50) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
    CHECKED_YN CHAR(1),
    REGIST_DATE DATE NOT NULL
);

COMMENT ON COLUMN C##NORAMOREDB.ALARM.ALARM_ID IS '알람번호';
COMMENT ON COLUMN C##NORAMOREDB.ALARM.ALARM_KIND IS '알람종류';
COMMENT ON COLUMN C##NORAMOREDB.ALARM.NATIVE_ID IS '출처ID'; 
COMMENT ON COLUMN C##NORAMOREDB.ALARM.RECEIVER_ID IS '수신자ID';
COMMENT ON COLUMN C##NORAMOREDB.ALARM.SENDER_ID IS '발신자ID';
COMMENT ON COLUMN C##NORAMOREDB.ALARM.CHECKED_YN IS '수신여부';
COMMENT ON COLUMN C##NORAMOREDB.ALARM.REGIST_DATE IS '발신일자';



CREATE SEQUENCE seq_alarm
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trigger_comm_recr
AFTER INSERT ON comm_recr
FOR EACH ROW
DECLARE
    receiver_id VARCHAR2(100);
BEGIN
    SELECT member_id INTO receiver_id
    FROM recr_board
    WHERE board_id = :NEW.board_id;

    INSERT INTO alarm 
    VALUES (seq_alarm.NEXTVAL, 'COMM_RECR', :NEW.comment_id, receiver_id, :NEW.member_id, 'N', SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER trigger_comm_free
AFTER INSERT ON comm_free
FOR EACH ROW
DECLARE
    receiver_id VARCHAR2(100);
BEGIN
    SELECT member_id INTO receiver_id
    FROM free_board
    WHERE board_id = :NEW.board_id;

    INSERT INTO alarm 
    VALUES (seq_alarm.NEXTVAL, 'COMM_FREE', :NEW.comment_id, receiver_id, :NEW.member_id, 'N', SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER trigger_recr_appl
AFTER INSERT ON recr_appl
FOR EACH ROW
DECLARE
    receiver_id VARCHAR2(100);
BEGIN
    SELECT member_id INTO receiver_id
    FROM recr_board
    WHERE board_id = :NEW.board_id;

    INSERT INTO alarm 
    VALUES (seq_alarm.NEXTVAL, 'RECR_APPL', :NEW.board_id, receiver_id, :NEW.member_id, 'N', SYSDATE);
END;
/

CREATE OR REPLACE PROCEDURE insert_sample_members AS
BEGIN
    FOR i IN 1..115 LOOP
        INSERT INTO MEMBER (
            MEMBER_ID, MEMBER_PWD, MEMBER_NICNAME, MEMBER_NAME, BIRTH, GENDER,
            EMAIL, ADDRESS, RESIGN, ADMIN_YN, SIGNTYPE, ACT_LIMIT,
            REGIST_DATE, MODIFIED_DATE
        ) VALUES (
            'user' || i, 'password' || i, 'nickname' || i, 'Name' || i, 
            TO_DATE('2000-01-01', 'YYYY-MM-DD'), 'M', 
            'user' || i || '@example.com', 'Address ' || i, 
            null, 'N', 'DIRECT', '0', SYSDATE, SYSDATE
        );
    END LOOP;
    COMMIT;
END insert_sample_members;
/

BEGIN
    insert_sample_members;
END;
/

update member
set act_limit = 1
where admin_yn <> 'Y'
and member_id like '%5';

update member_add
set report_count = 10
where member_id like '%4';
----------------------------------------------------------------------------------------------------------------------

DROP TABLE COMM_QNA CASCADE CONSTRAINTS;
DROP TABLE NOTICE_BOARD CASCADE CONSTRAINTS;
DROP TABLE QNA_BOARD CASCADE CONSTRAINTS;
                                    
                                         
CREATE TABLE C##NORAMOREDB.COMM_QNA                               
   (   BOARD_ID NUMBER NOT NULL ,                            
   COMMENT_NO NUMBER NOT NULL ,                            
   MEMBER_ID VARCHAR2(50) NOT NULL ,                            
   SUBSTANCE VARCHAR2(200) NOT NULL , 
   REF_COMMENT_NO INT DEFAULT 0,                           
   COMMENT_COUNT INT DEFAULT 0,
   REGIST_DT DATE DEFAULT SYSDATE NOT NULL ,                              
   LAST_UPD_DT DATE DEFAULT SYSDATE,                            
   CONSTRAINT COMM_QNA_PK PRIMARY KEY (BOARD_ID, COMMENT_NO) ,            
   CONSTRAINT COMMQ_1 FOREIGN KEY (MEMBER_ID)                           
   REFERENCES C##NORAMOREDB.MEMBER (MEMBER_ID) ON DELETE CASCADE                           
   );                            
                              
   COMMENT ON COLUMN C##NORAMOREDB.COMM_QNA.BOARD_ID IS 'QNA게시판ID';                     
   COMMENT ON COLUMN C##NORAMOREDB.COMM_QNA.COMMENT_NO IS '댓글번호';                     
   COMMENT ON COLUMN C##NORAMOREDB.COMM_QNA.MEMBER_ID IS '댓글 작성자';                     
   COMMENT ON COLUMN C##NORAMOREDB.COMM_QNA.SUBSTANCE IS '댓글 내용';                     
   COMMENT ON COLUMN C##NORAMOREDB.COMM_QNA.REGIST_DT IS '등록일자';                        
   COMMENT ON COLUMN C##NORAMOREDB.COMM_QNA.LAST_UPD_DT IS '최종수정일자';

COMMIT;


CREATE TABLE C##NORAMOREDB.NOTICE_BOARD
(
    BOARD_ID NUMBER NOT NULL ,
    MEMBER_ID VARCHAR2(50) NOT NULL ,
    TITLE VARCHAR2(50) NOT NULL ,
    SUBSTANCE VARCHAR2(200) NOT NULL ,
    READ_COUNT NUMBER,
    REGIST_DT DATE DEFAULT SYSDATE NOT NULL ,
    LAST_UPD_DT DATE DEFAULT SYSDATE,
    ORIGINAL_FILENAME VARCHAR2(50), 
    RENAME_FILENAME VARCHAR2(50),       
    CONSTRAINT NOTICE_BOARD_PK PRIMARY KEY (BOARD_ID) ,
    CONSTRAINT NOTIB_1 FOREIGN KEY (MEMBER_ID) REFERENCES C##NORAMOREDB.MEMBER (MEMBER_ID) ON DELETE CASCADE
); 
COMMENT ON COLUMN C##NORAMOREDB.NOTICE_BOARD.BOARD_ID IS '공지게시판ID';
COMMENT ON COLUMN C##NORAMOREDB.NOTICE_BOARD.MEMBER_ID IS '공지작성자';
COMMENT ON COLUMN C##NORAMOREDB.NOTICE_BOARD.TITLE IS '공지사항 제목';
COMMENT ON COLUMN C##NORAMOREDB.NOTICE_BOARD.SUBSTANCE IS '공지사항 내용';
COMMENT ON COLUMN C##NORAMOREDB.NOTICE_BOARD.READ_COUNT IS '조회수';
COMMENT ON COLUMN C##NORAMOREDB.NOTICE_BOARD.REGIST_DT IS '등록일자';
COMMENT ON COLUMN C##NORAMOREDB.NOTICE_BOARD.LAST_UPD_DT IS '최종수정일자';

COMMIT;

  CREATE TABLE "C##NORAMOREDB"."QNA_BOARD"                      
   (   BOARD_ID NUMBER NOT NULL ENABLE,
   MEMBER_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
   TITLE VARCHAR2(50 BYTE) NOT NULL ENABLE,                   
   SUBSTANCE VARCHAR2(200 BYTE) NOT NULL ENABLE,                   
   READ_COUNT NUMBER DEFAULT 0,                   
   REPORT_COUNT NUMBER DEFAULT 0,                   
   REGIST_DT DATE DEFAULT SYSDATE NOT NULL ENABLE,                   
   LAST_UPD_DT DATE, 
   COMMENT_COUNT INT DEFAULT 0,
   ORIGINAL_FILENAME VARCHAR2(50), 
   RENAME_FILENAME VARCHAR2(50),       
   CONSTRAINT "QNA_BOARD_PK" PRIMARY KEY ("BOARD_ID") ,      
   CONSTRAINT "QNAB_1" FOREIGN KEY ("MEMBER_ID")                  
   REFERENCES "C##NORAMOREDB"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE                  
   );                   
                     
   COMMENT ON COLUMN "C##NORAMOREDB"."QNA_BOARD"."BOARD_ID" IS '질문게시판ID';                     
   COMMENT ON COLUMN "C##NORAMOREDB"."QNA_BOARD"."MEMBER_ID" IS '질문작성자';                     
   COMMENT ON COLUMN "C##NORAMOREDB"."QNA_BOARD"."TITLE" IS '질문제목';                     
   COMMENT ON COLUMN "C##NORAMOREDB"."QNA_BOARD"."SUBSTANCE" IS '질문내용';                     
   COMMENT ON COLUMN "C##NORAMOREDB"."QNA_BOARD"."READ_COUNT" IS '조회수';                     
   COMMENT ON COLUMN "C##NORAMOREDB"."QNA_BOARD"."REPORT_COUNT" IS '신고 횟수';                     
   COMMENT ON COLUMN "C##NORAMOREDB"."QNA_BOARD"."REGIST_DT" IS '등록일자';                     
   COMMENT ON COLUMN "C##NORAMOREDB"."QNA_BOARD"."LAST_UPD_DT" IS '최종수정일자';
 

COMMIT;

-- member1-7 까지만

-- member insert

-- 샘플 데이터 추가
INSERT INTO MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NICNAME, MEMBER_NAME, BIRTH, GENDER, EMAIL, ADDRESS, PICTURE_FILE, RESIGN, ADMIN_YN, SIGNTYPE, ACT_LIMIT, REGIST_DATE, MODIFIED_DATE)
VALUES
('member1', 'password1', 'nick1', 'John Doe', TO_DATE('1990-01-01', 'YYYY-MM-DD'), 'M', 'john@example.com', '123 Main St, City, Country', NULL, NULL, 'N', 'direct', '0', SYSDATE, SYSDATE);
INSERT INTO MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NICNAME, MEMBER_NAME, BIRTH, GENDER, EMAIL, ADDRESS, PICTURE_FILE, RESIGN, ADMIN_YN, SIGNTYPE, ACT_LIMIT, REGIST_DATE, MODIFIED_DATE)
VALUES
('member2', 'password2', 'nick2', 'Jane Doe', TO_DATE('1991-02-02', 'YYYY-MM-DD'), 'F', 'jane@example.com', '456 Elm St, City, Country', NULL, NULL, 'N', 'kakao', '0', SYSDATE, SYSDATE);
INSERT INTO MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NICNAME, MEMBER_NAME, BIRTH, GENDER, EMAIL, ADDRESS, PICTURE_FILE, RESIGN, ADMIN_YN, SIGNTYPE, ACT_LIMIT, REGIST_DATE, MODIFIED_DATE)
VALUES
('member3', 'password3', 'nick3', 'Alice Smith', TO_DATE('1992-03-03', 'YYYY-MM-DD'), 'F', 'alice@example.com', '789 Oak St, City, Country', NULL, NULL, 'N', 'naver', '0', SYSDATE, SYSDATE);
INSERT INTO MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NICNAME, MEMBER_NAME, BIRTH, GENDER, EMAIL, ADDRESS, PICTURE_FILE, RESIGN, ADMIN_YN, SIGNTYPE, ACT_LIMIT, REGIST_DATE, MODIFIED_DATE)
VALUES
('member4', 'password4', 'nick4', 'Bob Smith', TO_DATE('1993-04-04', 'YYYY-MM-DD'), 'M', 'bob@example.com', '1011 Pine St, City, Country', NULL, NULL, 'N', 'google', '0', SYSDATE, SYSDATE);
INSERT INTO MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NICNAME, MEMBER_NAME, BIRTH, GENDER, EMAIL, ADDRESS, PICTURE_FILE, RESIGN, ADMIN_YN, SIGNTYPE, ACT_LIMIT, REGIST_DATE, MODIFIED_DATE)
VALUES
('member5', 'password5', 'nick5', 'Emily Johnson', TO_DATE('1994-05-05', 'YYYY-MM-DD'), 'F', 'emily@example.com', '1213 Cedar St, City, Country', NULL, NULL, 'N', 'direct', '0', SYSDATE, SYSDATE);
INSERT INTO MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NICNAME, MEMBER_NAME, BIRTH, GENDER, EMAIL, ADDRESS, PICTURE_FILE, RESIGN, ADMIN_YN, SIGNTYPE, ACT_LIMIT, REGIST_DATE, MODIFIED_DATE)
VALUES
('member6', 'password6', 'nick6', 'Michael Johnson', TO_DATE('1995-06-06', 'YYYY-MM-DD'), 'M', 'michael@example.com', '1415 Walnut St, City, Country', NULL, NULL, 'N', 'kakao', '0', SYSDATE, SYSDATE);
INSERT INTO MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NICNAME, MEMBER_NAME, BIRTH, GENDER, EMAIL, ADDRESS, PICTURE_FILE, RESIGN, ADMIN_YN, SIGNTYPE, ACT_LIMIT, REGIST_DATE, MODIFIED_DATE)
VALUES
('member7', 'password7', 'nick7', 'Emma Brown', TO_DATE('1996-07-07', 'YYYY-MM-DD'), 'F', 'emma@example.com', '1617 Maple St, City, Country', NULL, NULL, 'N', 'naver', '0', SYSDATE, SYSDATE);


--- 카테고리 : 1(볼링)

INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (8, 'member1', 1, '볼링관련 궁금한 사항이 있습니다.',  '안녕하세요, 볼링 관련 궁금한 점이 있는데 볼링의 규칙이 뭔가요?', 'original1.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (9, 'member2', 1, '볼링모임이 궁금한데요.',  '안녕하세요, 볼링모임 궁금한데 어디서 물어봐야 되나요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (10, 'member3', 1, '볼링치기 좋은 곳 추천부탁드립니다!',  '볼링치기 좋은 곳 추천부탁드립니다!!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (11, 'member4', 1, '안녕하세요~! 가입인사드립니다!!',  '안녕하세요~ 열심히 참여하겠습니다!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (12, 'member5', 1, '볼링치려는데 관절에 무리 괜찮나요?',  '볼링치려는데 관절상 무리는 없을까요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (13, 'member6', 1, '볼링 물품 추천바랍니다!',  '볼링 물품 추천해주세요.', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (14, 'member7', 1, '여름에 볼링치려니 덥네요..!',  '한여름에 볼링치려니 너무 덥습니다..!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (15, 'member1', 1, '볼링 물품 추천바래요~',  '볼링 물품 추천바래요~~', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (16, 'member2', 1, '볼링 칠 장소',  '볼링 칠 장소로 어디가 좋을까요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (17, 'member3', 1, '볼링 장소 추천 좀 해주세요!',  '신촌에서 볼링치려는데 볼링 칠 장소 좀 추천해주세요.', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );



-- 카테고리 : 2(클라이밍)

INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (18, 'member4', 2, '클라이밍관련 궁금한 사항이 있습니다.',  '안녕하세요, 클라이밍 관련 궁금한 점이 있는데 클라이밍의 규칙이 뭔가요?', 'original1.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (19, 'member5', 2, '클라이밍모임이 궁금한데요.',  '안녕하세요, 클라이밍모임 궁금한데 어디서 물어봐야 되나요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (20, 'member6', 2, '클라이밍하기 좋은 곳 추천부탁드립니다~~!',  '클라이밍하기 좋은 곳 추천부탁드립니다!!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (21, 'member7', 2, '안녕하세요~! 가입인사드립니다!!',  '안녕하세요~ 열심히 참여하겠습니다!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (22, 'member1', 2, '클라이밍하려는데 관절에 무리 괜찮나요?',  '클라이밍하려는데 관절상 무리는 없을까요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (23, 'member2', 2, '클라이밍 물품 추천바랍니다!',  '클라이밍 물품 추천해주세요.', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (24, 'member3', 2, '여름에 클라이밍하려니 덥네요..!',  '한여름에 클라이밍하려니 너무 덥습니다..!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (25, 'member4', 2, '클라이밍 물품 추천바래요~',  '클라이밍 물품 추천바래요~~', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (26, 'member5', 2, '클라이밍 할 장소',  '클라이밍 할 장소로 어디가 좋을까요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (27, 'member6', 2, '클라이밍 장소 추천 좀 해주세요!',  '신촌에서 클라이밍하려는데 볼링 칠 장소 좀 추천해주세요.', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );

-- 카테고리 : 3(사이클)

INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (28, 'member7', 3, '사이클관련 궁금한 사항이 있습니다.',  '안녕하세요, 사이클 관련 궁금한 점이 있는데 클라이밍의 규칙이 뭔가요?', 'original1.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (29, 'member1', 3, '사이클모임이 궁금한데요.',  '안녕하세요, 사이클모임 궁금한데 어디서 물어봐야 되나요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (30, 'member2', 3, '사이클하기 좋은 곳 추천부탁드립니다~~!',  '사이클하기 좋은 곳 추천부탁드립니다!!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (31, 'member3', 3, '안녕하세요~! 가입인사드립니다!!',  '안녕하세요~ 열심히 참여하겠습니다!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (32, 'member4', 3, '사이클하려는데 관절에 무리 괜찮나요?',  '사이클하려는데 관절상 무리는 없을까요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (33, 'member5', 3, '사이클 물품 추천바랍니다!',  '사이클 물품 추천해주세요.', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (34, 'member6', 3, '여름에 사이클하려니 덥네요..!',  '한여름에 사이클하려니 너무 덥습니다..!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (35, 'member7', 3, '사이클 물품 추천바래요~',  '사이클 물품 추천바래요~~', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (36, 'member1', 3, '사이클 할 장소',  '사이클 할 장소로 어디가 좋을까요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (37, 'member2', 3, '사이클 장소 추천 좀 해주세요!',  '신촌에서 사이클하려는데 장소 좀 추천해주세요.', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );

-- 카테고리 : 4(헬스)

INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (38, 'member3', 4, '헬스관련 궁금한 사항이 있습니다.',  '안녕하세요, 헬스 관련 궁금한 점이 있는데 헬스의 규칙이 뭔가요?', 'original1.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (39, 'member4', 4, '헬스모임이 궁금한데요.',  '안녕하세요, 헬스모임 궁금한데 어디서 물어봐야 되나요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (40, 'member5', 4, '헬스하기 좋은 곳 추천부탁드립니다~~!',  '헬스하기 좋은 곳 추천부탁드립니다!!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (41, 'member6', 4, '안녕하세요~! 가입인사드립니다!!',  '안녕하세요~ 열심히 참여하겠습니다!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (42, 'member7', 4, '헬스하려는데 관절에 무리 괜찮나요?',  '헬스하려는데 관절상 무리는 없을까요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (43, 'member1', 4, '헬스 물품 추천바랍니다!',  '헬스 물품 추천해주세요.', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (44, 'member2', 4, '여름에 헬스하려니 덥네요..!',  '한여름에 헬스하려니 너무 덥습니다..!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (45, 'member3', 4, '헬스 물품 추천바래요~',  '헬스 물품 추천바래요~~', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (46, 'member4', 4, '헬스 할 장소',  '헬스 장소로 어디가 좋을까요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (47, 'member5', 4, '헬스 장소 추천 좀 해주세요!',  '신촌에서 헬스하려는데 장소 좀 추천해주세요.', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );




-- 카테고리 : 5(수상스포츠)

INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (48, 'member6', 5, '수상스포츠관련 궁금한 사항이 있습니다.',  '안녕하세요, 수상스포츠 관련 궁금한 점이 있는데 헬스의 규칙이 뭔가요?', 'original1.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (49, 'member7', 5, '수상스포츠모임이 궁금한데요.',  '안녕하세요, 수상스포츠모임 궁금한데 어디서 물어봐야 되나요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (50, 'member1', 5, '수상스포츠하기 좋은 곳 추천부탁드립니다~~!',  '수상스포츠하기 좋은 곳 추천부탁드립니다!!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (51, 'member2', 5, '안녕하세요~! 가입인사드립니다!!',  '안녕하세요~ 열심히 참여하겠습니다!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (52, 'member3', 5, '수상스포츠하려는데 관절에 무리 괜찮나요?',  '수상스포츠하려는데 관절상 무리는 없을까요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (53, 'member4', 5, '수상스포츠 물품 추천바랍니다!',  '수상스포츠 물품 추천해주세요.', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (54, 'member5', 5, '여름에 수상스포츠하려니 덥네요..!',  '한여름에 수상스포츠하려니 너무 덥습니다..!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (55, 'member6', 5, '수상스포츠 물품 추천바래요~',  '수상스포츠 물품 추천바래요~~', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (56, 'member7', 5, '수상스포츠 할 장소',  '수상스포츠 장소로 어디가 좋을까요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (57, 'member1', 5, '수상스포츠 장소 추천 좀 해주세요!',  '가평에서 수상스포츠하려는데 장소 좀 추천해주세요.', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );


-- 카테고리 : 6(등산)

INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (58, 'member2', 6, '등산관련 궁금한 사항이 있습니다.',  '안녕하세요, 등산 관련 궁금한 점이 있는데 헬스의 규칙이 뭔가요?', 'original1.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (59, 'member3', 6, '등산모임이 궁금한데요.',  '안녕하세요, 등산모임 궁금한데 어디서 물어봐야 되나요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (60, 'member4', 6, '등산하기 좋은 곳 추천부탁드립니다~~!',  '등산하기 좋은 곳 추천부탁드립니다!!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (61, 'member5', 6, '안녕하세요~! 가입인사드립니다!!',  '안녕하세요~ 열심히 참여하겠습니다!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (62, 'member6', 6, '등산하려는데 관절에 무리 괜찮나요?',  '등산하려는데 관절상 무리는 없을까요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (63, 'member7', 6, '등산 물품 추천바랍니다!',  '등산 물품 추천해주세요.', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (64, 'member1', 6, '여름에 등산하려니 덥네요..!',  '한여름에 등산하려니 너무 덥습니다..!', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (65, 'member2', 6, '등산 물품 추천바래요~',  '등산 물품 추천바래요~~', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (66, 'member3', 6, '등산 할 장소',  '등산 장소로 어디가 좋을까요?', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );
INSERT INTO C##NORAMOREDB.FREE_BOARD(BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT) VALUES  (67, 'member4', 6, '등산 장소 추천 좀 해주세요!',  '신촌에서 등산하려는데 장소 좀 추천해주세요.', 'original3.jpg', 'rename3.jpg', 3, 4, 5, TO_DATE('2024-03-31 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),0 );



INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(68, 'member1', 1, '볼링의 매력', '최근에 다녀온 볼링 대회에서의 경험을 공유합니다.', 'bowling_event.jpg', 'bowling_event_renamed.jpg', 50, 20, 1, TO_DATE('2024-04-10', 'YYYY-MM-DD'), TO_DATE('2024-04-11', 'YYYY-MM-DD'), 7);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(69, 'member2', 1, '볼링 대회 후기', '지난 주말에 열린 볼링 대회에서의 참가 후기를 남깁니다.', 'bowling_competition.jpg', 'bowling_competition_renamed.jpg', 40, 15, 0, TO_DATE('2024-04-09', 'YYYY-MM-DD'), NULL, 4);

-- 클라이밍 카테고리
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(70, 'member3', 2, '최근 산행 이야기', '지난 주말에 다녀온 알프스 산행의 색다른 경험을 공유합니다.', 'alps_climbing.jpg', 'alps_climbing_renamed.jpg', 60, 25, 2, TO_DATE('2024-04-08', 'YYYY-MM-DD'), NULL, 12);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(71, 'member4', 2, '클라이밍의 매력', '산악인이라면 누구나 느낄 수 있는 클라이밍의 아름다움에 대해 이야기합니다.', NULL, NULL, 55, 18, 1, TO_DATE('2024-04-07', 'YYYY-MM-DD'), TO_DATE('2024-04-09', 'YYYY-MM-DD'), 6);

-- 사이클 카테고리
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(72, 'member5', 3, '자전거 여행 이야기', '최근에 다녀온 바이크 투어에서의 여행 경험을 공유합니다.', 'bike_tour.jpg', 'bike_tour_renamed.jpg', 70, 30, 0, TO_DATE('2024-04-06', 'YYYY-MM-DD'), NULL, 8);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(73, 'member6', 3, '자전거로 운동하기', '매일 아침 일찍 일어나서 자전거를 타고 운동하는 것의 효과에 대해 이야기합니다.', 'morning_cycling.jpg', 'morning_cycling_renamed.jpg', 45, 22, 3, TO_DATE('2024-04-05', 'YYYY-MM-DD'), TO_DATE('2024-04-06', 'YYYY-MM-DD'), 9);

-- 헬스 카테고리
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(74, 'member7', 4, '헬스장에서의 일상', '매일 헬스장에서의 트레이닝 일기를 기록하고 공유합니다.', 'gym_workout.jpg', 'gym_workout_renamed.jpg', 80, 35, 2, TO_DATE('2024-04-04', 'YYYY-MM-DD'), NULL, 11);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(75, 'member1', 4, '운동 습관 공유', '매일 운동하는 습관을 가지고 있는 사람들의 이야기를 들어보고 싶습니다.', 'daily_exercise.jpg', 'daily_exercise_renamed.jpg', 65, 28, 1, TO_DATE('2024-04-03', 'YYYY-MM-DD'), TO_DATE('2024-04-05', 'YYYY-MM-DD'), 5);

-- 수상스포츠 카테고리
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(76, 'member2', 5, '서핑의 묘미', '매일 바다에서 서핑하는 것이 주는 쾌감과 장점에 대해 이야기합니다.', 'surfing_fun.jpg', 'surfing_fun_renamed.jpg', 90, 40, 0, TO_DATE('2024-04-02', 'YYYY-MM-DD'), NULL, 13);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(77, 'member3', 5, '요트 타기 즐기기', '요트를 타고 바다를 항해하는 것이 주는 특별한 경험에 대해 이야기합니다.', 'yachting_experience.jpg', 'yachting_experience_renamed.jpg', 75, 33, 3,TO_DATE('2024-04-01', 'YYYY-MM-DD'), TO_DATE('2024-04-03', 'YYYY-MM-DD'), 6);

-- 등산 카테고리
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(78, 'member4', 6, '최근 산행 이야기', '최근 등산으로 여름의 느낌을 즐기고 온 소감을 공유합니다.', 'summer_hiking.jpg', 'summer_hiking_renamed.jpg', 85, 38, 1, TO_DATE('2024-03-31', 'YYYY-MM-DD'), TO_DATE('2024-04-01', 'YYYY-MM-DD'), 9);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(79, 'member5', 6, '등산 장비 공유', '등산을 즐기는 사람들을 위해 필요한 장비에 대해 소개합니다.', NULL, NULL, 70, 30, 2, TO_DATE('2024-03-30', 'YYYY-MM-DD'), NULL, 7);

-- 변경 사항 저장
COMMIT;

-- 볼링 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(80, 'member6', 1, '볼링 스킬 향상 팁', '볼링을 좋아하는 이들을 위한 스킬 향상을 위한 팁을 공유합니다.', 'bowling_tips.jpg', 'bowling_tips_renamed.jpg', 60, 25, 0, TO_DATE('2024-03-29', 'YYYY-MM-DD'), NULL, 4);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(81, 'member7', 1, '볼링 장비 추천', '최신 볼링 장비 추천과 사용 후기를 공유합니다.', NULL, NULL, 55, 20, 1, TO_DATE('2024-03-28', 'YYYY-MM-DD'), TO_DATE('2024-03-29', 'YYYY-MM-DD'), 8);


commit;







-- 클라이밍 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(82, 'member1', 2, '암벽 등반 이야기', '최근에 다녀온 암벽 등반에서의 도전과 성취를 공유합니다.', 'rock_climbing.jpg', 'rock_climbing_renamed.jpg', 75, 30, 2, TO_DATE('2024-03-27', 'YYYY-MM-DD'), NULL, 10);
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(83, 'member2', 2, '천장을 향한 도전', '난이도 높은 암벽을 정복하기 위한 도전 이야기를 나눕니다.', 'extreme_climbing.jpg', 'extreme_climbing_renamed.jpg', 65, 28, 0, TO_DATE('2024-03-26', 'YYYY-MM-DD'), TO_DATE('2024-03-27', 'YYYY-MM-DD'), 6);

-- 사이클 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(84, 'member3', 3, '자전거 유지보수 팁', '자전거를 유지보수하고 관리하는 노하우를 공유합니다.', 'bike_maintenance.jpg', 'bike_maintenance_renamed.jpg', 70, 32, 1, TO_DATE('2024-03-25', 'YYYY-MM-DD'), NULL, 8);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(85, 'member4', 3, '서울 자전거 여행', '서울에서 즐길 수 있는 자전거 여행 코스와 경험을 공유합니다.', NULL, NULL, 55, 22, 0, TO_DATE('2024-03-24', 'YYYY-MM-DD'), TO_DATE('2024-03-25', 'YYYY-MM-DD'), 7);

-- 헬스 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(86, 'member5', 4, '집에서 할 수 있는 헬스 운동', '집에서 쉽게 할 수 있는 헬스 운동 및 근육 효과에 대해 이야기합니다.', 'home_workout.jpg', 'home_workout_renamed.jpg', 80, 35, 1, TO_DATE('2024-03-23', 'YYYY-MM-DD'), NULL, 9);
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(87, 'member6', 4, '필라테스 체험 후기', '최근에 체험한 필라테스 수업 후기와 효과를 공유합니다.', 'pilates_experience.jpg', 'pilates_experience_renamed.jpg', 65, 28, 0, TO_DATE('2024-03-22', 'YYYY-MM-DD'), TO_DATE('2024-03-23', 'YYYY-MM-DD'), 6);

-- 수상스포츠 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(88, 'member7', 5, '서핑 장비 리뷰', '최신 서핑 장비의 장단점과 사용 후기를 소개합니다.', 'surfboard_review.jpg', 'surfboard_review_renamed.jpg', 90, 40, 0, TO_DATE('2024-03-21', 'YYYY-MM-DD'), NULL, 11);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(89, 'member1', 5, '요트 타고 여행기', '요트를 타고 여행한 경험을 공유하고 추천하는 여행지를 소개합니다.', 'yachting_journey.jpg', 'yachting_journey_renamed.jpg', 75, 33, 1, TO_DATE('2024-03-20', 'YYYY-MM-DD'), TO_DATE('2024-03-21', 'YYYY-MM-DD'), 8);

-- 등산 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(90, 'member2', 6, '가을 등산 추천', '가을에 어울리는 아름다운 등산 코스를 소개하고 추천합니다.', 'autumn_hiking.jpg', 'autumn_hiking_renamed.jpg', 85, 38, 0, TO_DATE('2024-03-19', 'YYYY-MM-DD'), NULL, 10);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(91, 'member3', 6, '완경산 등반 후기', '최근 완경산 등반에서의 경험과 힘든 여정을 공유합니다.', NULL, NULL, 70, 30, 2, TO_DATE('2024-03-18', 'YYYY-MM-DD'), TO_DATE('2024-03-19', 'YYYY-MM-DD'), 7);


-- 볼링 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(92, 'member4', 1, '볼링 스타일링 팁', '볼링을 할 때 자세와 스타일링에 대한 팁과 기술을 소개합니다.', 'bowling_style.jpg', 'bowling_style_renamed.jpg', 60, 25, 1, TO_DATE('2024-03-17', 'YYYY-MM-DD'), NULL, 5);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(93, 'member5', 1, '신규 볼링장 오픈 소식', '신규 볼링장이 오픈되었으니 함께 볼링을 즐겨봅시다!', 'new_bowling_alley.jpg', 'new_bowling_alley_renamed.jpg', 55, 20, 0, TO_DATE('2024-03-16', 'YYYY-MM-DD'), TO_DATE('2024-03-17', 'YYYY-MM-DD'), 9);

-- 클라이밍 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(94, 'member6', 2, '유명 암벽 등반지 추천', '전 세계에서 인정받는 유명한 암벽 등반지를 소개합니다.', 'famous_climbing_spot.jpg', 'famous_climbing_spot_renamed.jpg', 75, 30, 2, TO_DATE('2024-03-15', 'YYYY-MM-DD'), NULL, 11);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(95, 'member7', 2, '암벽 등반에 필요한 장비', '암벽 등반을 시작하기 위해 필요한 기본 장비를 소개합니다.', 'climbing_gear.jpg', 'climbing_gear_renamed.jpg', 65, 28, 0, TO_DATE('2024-03-14', 'YYYY-MM-DD'), TO_DATE('2024-03-15', 'YYYY-MM-DD'), 7);

-- 사이클 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(96, 'member1', 3, '마운틴 자전거 추천', '마운틴 바이크를 구매하기 전에 고려해야 할 사항을 알아보고 추천합니다.', 'mountain_bike.jpg', 'mountain_bike_renamed.jpg', 70, 32, 1, TO_DATE('2024-03-13', 'YYYY-MM-DD'), NULL, 8);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(97, 'member2', 3, '자전거 여행지 추천', '자전거 여행을 계획 중인 이들을 위한 추천 여행지를 소개합니다.', NULL, NULL, 55, 22, 0, TO_DATE('2024-03-12', 'YYYY-MM-DD'), TO_DATE('2024-03-13', 'YYYY-MM-DD'), 6);

-- 헬스 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(98, 'member3', 4, '홈 트레이닝 팁', '집에서 할 수 있는 간편하면서 효과적인 홈 트레이닝 팁을 소개합니다.', 'home_training.jpg', 'home_training_renamed.jpg', 80, 35, 1, TO_DATE('2024-03-11', 'YYYY-MM-DD'), NULL, 9);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(99, 'member4', 4, '크로스핏 체험 후기', '최근 체험한 크로스핏 수업 후기와 효과를 공유합니다.', 'crossfit_experience.jpg', 'crossfit_experience_renamed.jpg', 65, 28, 0, TO_DATE('2024-03-10', 'YYYY-MM-DD'), TO_DATE('2024-03-11', 'YYYY-MM-DD'), 6);

-- 수상스포츠 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(100, 'member5', 5, '서핑 여행지 추천', '서핑을 즐기기에 최적의 여행지를 추천합니다.', 'surfing_destination.jpg', 'surfing_destination_renamed.jpg', 90, 40, 0, TO_DATE('2024-03-09', 'YYYY-MM-DD'), NULL, 11);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(101, 'member6', 5, '요트 장비 소개', '요트를 타기 위해 필요한 다양한 장비와 사용법을 소개합니다.', 'yachting_equipment.jpg', 'yachting_equipment_renamed.jpg', 75, 33, 1, TO_DATE('2024-03-08', 'YYYY-MM-DD'), TO_DATE('2024-03-09', 'YYYY-MM-DD'), 8);

-- 등산 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(102, 'member7', 6, '봄 산행 계획', '봄철 산행을 계획 중인 이들을 위한 산행 코스 추천과 준비 사항을 소개합니다.', 'spring_hiking.jpg', 'spring_hiking_renamed.jpg', 85, 38, 0, TO_DATE('2024-03-07', 'YYYY-MM-DD'), NULL, 10);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(103, 'member1', 6, '한라산 트레킹 후기', '한라산을 트레킹한 후기와 다양한 경험을 공유합니다.', NULL, NULL, 70, 30, 2, TO_DATE('2024-03-06', 'YYYY-MM-DD'), TO_DATE('2024-03-07', 'YYYY-MM-DD'), 7);

-- 변경 사항 저장
COMMIT;

-- 볼링 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(104, 'member2', 1, '볼링 대회 참가 후기', '최근 참가한 볼링 대회에서의 경험과 성과를 공유합니다.', 'bowling_tournament.jpg', 'bowling_tournament_renamed.jpg', 60, 25, 1, TO_DATE('2024-03-05', 'YYYY-MM-DD'), NULL, 5);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(105, 'member3', 1, '신기록 돌파 이야기', '최근에 달성한 개인 신기록에 대한 이야기를 나눕니다.', 'personal_best.jpg', 'personal_best_renamed.jpg', 55, 20, 0, TO_DATE('2024-03-04', 'YYYY-MM-DD'), TO_DATE('2024-03-05', 'YYYY-MM-DD'), 9);

-- 클라이밍 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(106, 'member4', 2, '암벽 등반 필수 장비', '암벽 등반을 할 때 필요한 필수 장비와 사용법에 대해 알아봅니다.', 'climbing_essentials.jpg', 'climbing_essentials_renamed.jpg', 75, 30, 2, TO_DATE('2024-03-03', 'YYYY-MM-DD'), NULL, 11);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(107, 'member5', 2, '어려운 산악 등반 이야기', '고난이도의 산악 등반에서의 경험과 도전을 공유합니다.', 'mountaineering_challenge.jpg', 'mountaineering_challenge_renamed.jpg', 65, 28, 0, TO_DATE('2024-03-02', 'YYYY-MM-DD'), TO_DATE('2024-03-03', 'YYYY-MM-DD'), 7);

-- 사이클 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(108, 'member6', 3, '자전거 여행의 매력', '자전거 여행을 즐기는 이유와 여행 중 느낀 감동을 나눕니다.', 'biking_adventure.jpg', 'biking_adventure_renamed.jpg', 70, 32, 1, TO_DATE('2024-03-01', 'YYYY-MM-DD'), NULL, 8);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(109, 'member7', 3, '도로 자전거 용품 추천', '도로 자전거를 타기 위해 필요한 다양한 용품을 추천합니다.', NULL, NULL, 55, 22, 0, TO_DATE('2024-02-29', 'YYYY-MM-DD'), TO_DATE('2024-03-01', 'YYYY-MM-DD'), 6);

-- 헬스 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(110, 'member1', 4, '헬스장 가입 후기', '최근 가입한 헬스장에서의 경험과 효과를 공유합니다.', 'gym_membership.jpg', 'gym_membership_renamed.jpg', 80, 35, 1, TO_DATE('2024-02-28', 'YYYY-MM-DD'), NULL, 9);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(111, 'member2', 4, '웨이트 트레이닝 팁', '웨이트 트레이닝을 위한 기술적인 팁과 노하우를 소개합니다.', 'weightlifting_tips.jpg', 'weightlifting_tips_renamed.jpg', 65,


-- 헬스 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(112, 'member3', 4, '헬스장 가입 후기', '최근 가입한 헬스장에서의 경험과 효과를 공유합니다.', 'gym_membership.jpg', 'gym_membership_renamed.jpg', 80, 35, 1, TO_DATE('2024-02-28', 'YYYY-MM-DD'), NULL, 9);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(113, 'member4', 4, '웨이트 트레이닝 팁', '웨이트 트레이닝을 위한 기술적인 팁과 노하우를 소개합니다.', 'weightlifting_tips.jpg', 'weightlifting_tips_renamed.jpg', 65, 28, 0, TO_DATE('2024-02-27', 'YYYY-MM-DD'), TO_DATE('2024-02-28', 'YYYY-MM-DD'), 6);

-- 수상스포츠 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(114, 'member5', 5, '수상 스포츠 트릭 배우기', '수상 스포츠에서의 다양한 트릭을 배우고 연습하는 방법을 소개합니다.', 'watersports_tricks.jpg', 'watersports_tricks_renamed.jpg', 90, 40, 0, TO_DATE('2024-02-26', 'YYYY-MM-DD'), NULL, 11);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(115, 'member6', 5, '요트 여행 후기', '요트를 이용한 여행에서의 경험과 추억을 공유합니다.', 'sailing_adventure.jpg', 'sailing_adventure_renamed.jpg', 75, 33, 1, TO_DATE('2024-02-25', 'YYYY-MM-DD'), TO_DATE('2024-02-26', 'YYYY-MM-DD'), 8);

-- 등산 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(116, 'member7', 6, '등산을 통한 스트레스 해소법', '등산을 통해 일상에서의 스트레스를 효과적으로 해소하는 방법을 소개합니다.', 'stress_relief_hiking.jpg', 'stress_relief_hiking_renamed.jpg', 85, 38, 0, TO_DATE('2024-02-24', 'YYYY-MM-DD'), NULL, 10);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(117, 'member1', 6, '고산 교육 프로그램 후기', '고산에서의 교육적인 등반 프로그램을 참여한 후기와 경험을 공유합니다.', NULL, NULL, 70, 30, 2, TO_DATE('2024-02-23', 'YYYY-MM-DD'), TO_DATE('2024-02-24', 'YYYY-MM-DD'), 7);

-- 변경 사항 저장
COMMIT;


-- 볼링 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(118, 'member2', 1, '볼링 기술 향상을 위한 비밀', '볼링 기술을 향상시키기 위한 비밀을 공유합니다.', 'bowling_technique.jpg', 'bowling_technique_renamed.jpg', 60, 25, 1, TO_DATE('2024-02-22', 'YYYY-MM-DD'), NULL, 5);
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(119, 'member3', 1, '볼링 대회 참가를 위한 조언', '볼링 대회에 참가하기 전에 고려해야 할 조언을 제공합니다.', 'bowling_competition.jpg', 'bowling_competition_renamed.jpg', 55, 20, 0, TO_DATE('2024-02-21', 'YYYY-MM-DD'), TO_DATE('2024-02-22', 'YYYY-MM-DD'), 9);

-- 클라이밍 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(120, 'member4', 2, '연약한 시작자를 위한 암벽 등반 팁', '암벽 등반을 시작하는 사람들을 위한 팁과 가이드를 제공합니다.', 'climbing_tips.jpg', 'climbing_tips_renamed.jpg', 75, 30, 2, TO_DATE('2024-02-20', 'YYYY-MM-DD'), NULL, 11);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(121, 'member5', 2, '암벽 등반을 위한 트레이닝 계획', '암벽 등반을 위한 효과적인 트레이닝 계획과 방법을 소개합니다.', 'climbing_training.jpg', 'climbing_training_renamed.jpg', 65, 28, 0, TO_DATE('2024-02-19', 'YYYY-MM-DD'), TO_DATE('2024-02-20', 'YYYY-MM-DD'), 7);

-- 사이클 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(122, 'member6', 3, '최신 자전거 기술 소식', '최신 자전거 기술과 트렌드에 대한 소식을 전합니다.', 'latest_bike_tech.jpg', 'latest_bike_tech_renamed.jpg', 70, 32, 1, TO_DATE('2024-02-18', 'YYYY-MM-DD'), NULL, 8);
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(123, 'member7', 3, '자전거 여행에서의 안전 수칙', '자전거 여행 중 안전을 위해 반드시 알아야 할 수칙을 소개합니다.', NULL, NULL, 55, 22, 0, TO_DATE('2024-02-17', 'YYYY-MM-DD'), TO_DATE('2024-02-18', 'YYYY-MM-DD'), 6);

-- 헬스 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(124, 'member1', 4, '근력 향상을 위한 식단', '근력 향상을 위해 권장되는 식단 및 영양 제품에 대해 알아봅니다.', 'muscle_building_diet.jpg', 'muscle_building_diet_renamed.jpg', 80, 35, 1, TO_DATE('2024-02-16', 'YYYY-MM-DD'), NULL, 9);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(125, 'member2', 4, '핏니스 전문가와의 인터뷰', '핏니스 전문가와의 인터뷰를 통해 건강한 운동 및 식생활에 대한 정보를 얻습니다.', 'fitness_expert_interview.jpg', 'fitness_expert_interview_renamed.jpg', 65, 28, 0, TO_DATE('2024-02-15', 'YYYY-MM-DD'), TO_DATE('2024-02-16', 'YYYY-MM-DD'), 6);

-- 수상스포츠 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(126, 'member3', 5, '서핑 입문자를 위한 꿀팁', '서핑을 처음 시작하는 분들을 위한 팁과 조언을 공유합니다.', 'surfing_beginner_tips.jpg', 'surfing_beginner_tips_renamed.jpg', 90, 40, 0, TO_DATE('2024-02-14', 'YYYY-MM-DD'), NULL, 11);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(127, 'member4', 5, '스쿠버 다이빙의 아름다움', '스쿠버 다이빙을 통해 경험하는 해저의 아름다움을 이야기합니다.', 'scuba_diving_beauty.jpg', 'scuba_diving_beauty_renamed.jpg', 75, 33, 1, TO_DATE('2024-02-13', 'YYYY-MM-DD'), TO_DATE('2024-02-14', 'YYYY-MM-DD'), 8);

-- 등산 카테고리 (계속)
INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(128, 'member5', 6, '하이킹을 통한 자연 치유', '하이킹을 통해 자연 속에서 얻는 심신 안정과 치유의 힘을 이야기합니다.', 'nature_healing_hike.jpg', 'nature_healing_hike_renamed.jpg', 85, 38, 0, TO_DATE('2024-02-12', 'YYYY-MM-DD'), NULL, 10);

INSERT INTO C##NORAMOREDB.FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY_ID, TITLE, CONTEXT, FREE_ORIGINAL_FILENAME, FREE_RENAME_FILENAME, READ_COUNT, LIKE_COUNT, REPORT_COUNT, REGIST_DATE, LAST_UPD_DATE, COMMENT_COUNT)
VALUES
(129, 'member6', 6, '산악 자연 환경 보전 활동', '산악 자연 환경을 보존하고 보호하기 위한 다양한 활동과 봉사활동을 소개합니다.', NULL, NULL, 70, 30, 2, TO_DATE('2024-02-11', 'YYYY-MM-DD'), TO_DATE('2024-02-12', 'YYYY-MM-DD'), 7);

-- 변경 사항 저장
COMMIT;







