-- 생성시 "C##TESTWEB"를 다른글자로 일괄 변경후 실행할 것.
-- 자동생성 스크립트이므로 꼭, 내용을 확인할 것.
-- INSERT 추가 검토할 것.
-- 변경시 변경버전 추가하고 수정내용 아래와 작성할 것.

/*
	ver 0.1 / 김영활 / 2024.04.11
		: 미팅 추가
		: 알람 메인테이블 삭제
		: 통합검색 카테고리 칼럼 삭제
		: 트리거 삭제		
		: 샘플데이터 삭제		
		
	ver 0.9 / 전상우 / 2024.04.09
		: 4-2 게시판 테이블 B_ORIGINFILENAME, B_RENAMEFILENAME 컬럼 위치 변경

	ver 0.8 / 전상우 / 2024.04.07
		: 4-2 게시물 테이블 B_ORIGINFILENAME, B_RENAMEFILENAME 컬럼 추가 및 코맨트 추가
	
	ver 0.7 / 전상우 / 2024.04.04
		: 4-2 게시물 테이블 B_ORIGINFILENAME, B_RENAMEFILENAME 컬럼 추가

	ver 0.6 / 이승철 / 2024.04.04
		: 1. TB_MEMBER 드랍 테이블 추가
		: 1-1. 드랍시퀀스 추가
		: 2. TB_MEMBER 테이블 M_PASSWD컬럼 NO NULL 삭제
		: 2-1. TB_SOCIAL_MEMBER 소셜멤버 테이블 생성
		: 2-1. SEQUENCE SM_SEQ 소셜 회원 고유 번호 시퀀스 추가

	ver 0.5 / 홍은비 / 2024.03.27
		: 4-1. 카테고리 테이블 CT_NAME 컬럼 추가
		: 10. INSERT문 추가	

	ver 0.4 / 전상우 / 2024.03.25
		: 4-4 Board File 삭제

	ver 0.3 / 김민식 / 2024.03.21
		: edate, odate, reader 등 오타 수정

	ver 0.21 / 아무개 / 2024.03.19
		: 테이블 TB_MEMBER 의 칼럼명 M_NO 에서 M_NUM 으로 변경
		: 테이블 TB_BOARD_FILE 삭제
		: 테이블 TB_CHATROOMUSER_1 추가
	
	ver 0.2 / 홍길동 / 2024.03.19
		: 테이블 TB_MEMBER 의 칼럼명 M_NO 에서 M_NUM 으로 변경
		: 테이블 TB_BOARD_FILE 삭제
		: 테이블 TB_CHATROOMUSER_1 추가	

	ver 0.1 / 김영활 / 2024.03.19
		: 최초 작성
*/


-- 1. 기존테이블 삭제
DROP TABLE TB_MEMBER CASCADE CONSTRAINTS;
DROP TABLE TB_SOCIAL_MEMBER CASCADE CONSTRAINTS;
DROP TABLE TB_TEAM CASCADE CONSTRAINTS;
DROP TABLE TB_TEAM_USER CASCADE CONSTRAINTS;

DROP TABLE TB_BOARD CASCADE CONSTRAINTS;

DROP TABLE TB_MEETING CASCADE CONSTRAINTS;

DROP TABLE TB_DRIVE CASCADE CONSTRAINTS;
DROP TABLE TB_DRIVE_FOLDER CASCADE CONSTRAINTS;
DROP TABLE TB_DRIVE_FILE CASCADE CONSTRAINTS;

DROP TABLE TB_CALENDER CASCADE CONSTRAINTS;

DROP TABLE TB_ALARM_CHECK CASCADE CONSTRAINTS;
DROP TABLE TB_SEARCH CASCADE CONSTRAINTS;

--1-2 시퀀스 삭제
DROP SEQUENCE M_SEQ; 
DROP SEQUENCE SM_SEQ;


-- 2. 회원 테이블
CREATE TABLE TB_MEMBER 
(	
	M_NO NUMBER NOT NULL, 
	M_NAME VARCHAR2(100 BYTE) NOT NULL, 
	M_EMAIL VARCHAR2(200 BYTE) NOT NULL, 
	M_PASSWD VARCHAR2(100 BYTE), 
	M_EDATE DATE NOT NULL, 
	M_ODATE DATE, 
	CONSTRAINT TB_MEMBER_PK PRIMARY KEY (M_NO)
);

COMMENT ON COLUMN TB_MEMBER.M_NO IS '고유번호';
COMMENT ON COLUMN TB_MEMBER.M_NAME IS '이름';
COMMENT ON COLUMN TB_MEMBER.M_EMAIL IS '이메일(아이디)';
COMMENT ON COLUMN TB_MEMBER.M_PASSWD IS '비밀번호';
COMMENT ON COLUMN TB_MEMBER.M_EDATE IS '가입일';
COMMENT ON COLUMN TB_MEMBER.M_ODATE IS '탈퇴일';

-- 회원 고유 번호 시퀀스
CREATE SEQUENCE M_SEQ
INCREMENT BY 1
START WITH 100
NOCYCLE
NOCACHE;

-- 2-1. 소셜회원 테이블

CREATE TABLE TB_SOCIAL_MEMBER
(
    SM_NO NUMBER, 
    SM_SNO NUMBER NOT NULL,
    SM_ID VARCHAR2(100 BYTE) NOT NULL,
    SM_EMAIL VARCHAR2(200 BYTE) NOT NULL,	
    SM_NAME VARCHAR2(100 BYTE) NOT NULL,
    SM_TYPE VARCHAR2(100 BYTE) NOT NULL,
    SM_EDATE DATE NOT NULL,
    SM_ODATE DATE,
    
    CONSTRAINT TB_SOCIAL_MEMBER_PK PRIMARY KEY (SM_SNO)
);

COMMENT ON COLUMN TB_SOCIAL_MEMBER.SM_NO IS '고유번호';
COMMENT ON COLUMN TB_SOCIAL_MEMBER.SM_SNO IS '소셜계정고유번호';
COMMENT ON COLUMN TB_SOCIAL_MEMBER.SM_ID IS '소셜계정아이디';
COMMENT ON COLUMN TB_SOCIAL_MEMBER.SM_EMAIL IS '소셜계정이메일';
COMMENT ON COLUMN TB_SOCIAL_MEMBER.SM_NAME IS '소셜계정이름';
COMMENT ON COLUMN TB_SOCIAL_MEMBER.SM_TYPE IS '소셜타입';
COMMENT ON COLUMN TB_SOCIAL_MEMBER.SM_EDATE IS '소셜계정가입일';
COMMENT ON COLUMN TB_SOCIAL_MEMBER.SM_ODATE IS '소셜계정탈퇴일';

-- 소셜 회원 고유 번호 시퀀스

CREATE SEQUENCE SM_SEQ
INCREMENT BY 1
START WITH 1000
NOCYCLE
NOCACHE;


-- 3-1. 팀 테이블
CREATE TABLE TB_TEAM
(	
	T_NO NUMBER NOT NULL, 
	T_MID NUMBER NOT NULL, 
	T_NAME VARCHAR2(20 BYTE), 
	T_CDATE DATE, 
	CONSTRAINT TB_TEAM_PK PRIMARY KEY (T_NO), 
	CONSTRAINT TB_TEAM_FK1 FOREIGN KEY (T_MID) REFERENCES TB_MEMBER (M_NO)
);

COMMENT ON COLUMN TB_TEAM.T_NO IS '팀 고유번호';
COMMENT ON COLUMN TB_TEAM.T_MID IS '팀장, 회원 고유번호';
COMMENT ON COLUMN TB_TEAM.T_NAME IS '팀명';
COMMENT ON COLUMN TB_TEAM.T_CDATE IS '팀 개설일';


-- 3-2. 팀원 테이블
CREATE TABLE TB_TEAM_USER 
(   
   TU_TID NUMBER NOT NULL, 
   TU_MID NUMBER, 
   TU_EDATE DATE NOT NULL, 
   TU_ODATE DATE, 
   TU_LEADER CHAR(1 BYTE) DEFAULT 'N' NOT NULL,
   TU_INVITED CHAR(1 BYTE) DEFAULT 'N' NOT NULL,
   TU_EMAIL VARCHAR2(20 BYTE) NOT NULL, 
   CONSTRAINT TB_TEAM_USER_PK PRIMARY KEY (TU_TID, TU_MID), 
   CONSTRAINT TB_TEAM_USER_FK1 FOREIGN KEY (TU_TID) REFERENCES TB_TEAM (T_NO) ON DELETE CASCADE
);

COMMENT ON COLUMN TB_TEAM_USER.TU_TID IS '팀 고유번호';
COMMENT ON COLUMN TB_TEAM_USER.TU_MID IS '회원 고유번호';
COMMENT ON COLUMN TB_TEAM_USER.TU_EDATE IS '팀 가입일';
COMMENT ON COLUMN TB_TEAM_USER.TU_ODATE IS '팀 탈퇴일';
COMMENT ON COLUMN TB_TEAM_USER.TU_LEADER IS '팀 리더여부';
COMMENT ON COLUMN TB_TEAM_USER.TU_INVITED IS '팀 초대여부';
COMMENT ON COLUMN TB_TEAM_USER.TU_EMAIL IS '팀원 이메일';


-- 4-2. 게시물 테이블
CREATE TABLE TB_BOARD
(	
	B_NO NUMBER NOT NULL, 
	B_TITLE VARCHAR2(200 BYTE) NOT NULL, 
	B_CONTENT VARCHAR2(4000 BYTE) NOT NULL, 
	B_ORIGINFILENAME VARCHAR2(100 BYTE),
	B_RENAMEFILENAME VARCHAR2(100 BYTE),
	B_CRUID NUMBER NOT NULL, 
	B_NAME VARCHAR2(50 BYTE) NOT NULL, 
	B_ID VARCHAR2(200 BYTE) NOT NULL, 
	B_CDATE DATE DEFAULT sysdate NOT NULL, 
	B_UDATE DATE, 
	B_CTID NUMBER, 
	B_TID NUMBER NOT NULL,
	CONSTRAINT TB_BOARD_PK PRIMARY KEY (B_TID, B_NO), 
	CONSTRAINT TB_BOARD_FK2 FOREIGN KEY (B_TID, B_CRUID) REFERENCES TB_TEAM_USER (TU_TID, TU_MID), 
	CONSTRAINT TB_BOARD_FK3 FOREIGN KEY (B_TID) REFERENCES TB_TEAM (T_NO)
);

COMMENT ON COLUMN TB_BOARD.B_NO IS '게시물 고유번호';
COMMENT ON COLUMN TB_BOARD.B_TITLE IS '게시물 제목';
COMMENT ON COLUMN TB_BOARD.B_CONTENT IS '게시물 내용';
COMMENT ON COLUMN TB_BOARD.B_ORIGINFILENAME  IS '원본첨부파일명';
COMMENT ON COLUMN TB_BOARD.B_RENAMEFILENAME IS '바뀐첨부파일명';
COMMENT ON COLUMN TB_BOARD.B_CRUID IS '게시물 작성자의 고유번호';
COMMENT ON COLUMN TB_BOARD.B_NAME IS '게시물 작성자의 이름';
COMMENT ON COLUMN TB_BOARD.B_ID IS '게시물 작성자의 아이디';
COMMENT ON COLUMN TB_BOARD.B_CDATE IS '게시물 생성일';
COMMENT ON COLUMN TB_BOARD.B_UDATE IS '게시물 수정일';
COMMENT ON COLUMN TB_BOARD.B_CTID IS '카테고리 고유번호';
COMMENT ON COLUMN TB_BOARD.B_TID IS '팀 고유번호';



-- METTING(회의) 테이블
CREATE TABLE TB_MEETING (
        MT_ID NUMBER CONSTRAINT PK_NOTICENO PRIMARY KEY,
        MT_TITLE VARCHAR2(50) NOT NULL,
        MT_DATE DATE DEFAULT SYSDATE,
        MT_UPDATE DATE,
        MT_MID NUMBER NOT NULL,
        MT_WRITER VARCHAR2(50) NOT NULL,
        MT_WRITER_ID VARCHAR2(200) NOT NULL,
        MT_CONTENT VARCHAR2(2000),
        MT_ORIGINAL_FILENAME VARCHAR2(100),
        MT_RENAME_FILENAME VARCHAR2(100),
        MT_IMPORTANCE CHAR(1) DEFAULT 'N',  
        MT_READCOUNT NUMBER DEFAULT 1 NOT NULL,
        MT_TID NUMBER NOT NULL
);

COMMENT ON COLUMN TB_MEETING.MT_ID IS '회의 번호';
COMMENT ON COLUMN TB_MEETING.MT_TITLE IS '회의 제목';
COMMENT ON COLUMN TB_MEETING.MT_DATE IS '회의 등록날짜';
COMMENT ON COLUMN TB_MEETING.MT_UPDATE IS '회의 수정날짜';
COMMENT ON COLUMN TB_MEETING.MT_MID IS '회의 작성자 고유번호';
COMMENT ON COLUMN TB_MEETING.MT_WRITER IS '회의 작성자 이름';
COMMENT ON COLUMN TB_MEETING.MT_WRITER_ID IS '회의 작성자 아이디';
COMMENT ON COLUMN TB_MEETING.MT_CONTENT IS '회의 내용';
COMMENT ON COLUMN TB_MEETING.MT_ORIGINAL_FILENAME IS '회의 원본 첨부파일명';
COMMENT ON COLUMN TB_MEETING.MT_RENAME_FILENAME IS '회의 바뀐 첨부파일명';
COMMENT ON COLUMN TB_MEETING.MT_IMPORTANCE IS '회의 중요도';
COMMENT ON COLUMN TB_MEETING.MT_READCOUNT IS '회의 조회수';
COMMENT ON COLUMN TB_MEETING.MT_TID  IS '팀 고유번호';



-- 6-1. 드라이브 테이블
CREATE TABLE TB_DRIVE 
(	
	D_NO NUMBER NOT NULL, 
	D_NAME VARCHAR2(50 BYTE) NOT NULL, 
	D_CDATE DATE NOT NULL, 
	D_UDATE DATE, 
	D_PUB CHAR(1 BYTE) DEFAULT 'Y' NOT NULL, 
	D_TRCAN CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	D_CRUID NUMBER NOT NULL, 
	D_TID NUMBER NOT NULL, 
	CONSTRAINT TB_DRIVE_PK PRIMARY KEY (D_TID, D_NO), 
	CONSTRAINT TB_DRIVE_FK1 FOREIGN KEY (D_TID, D_CRUID) REFERENCES TB_TEAM_USER (TU_TID, TU_MID), 
	CONSTRAINT TB_DRIVE_FK2 FOREIGN KEY (D_TID) REFERENCES TB_TEAM (T_NO)
);

COMMENT ON COLUMN TB_DRIVE.D_NO IS '드라이브 고유번호';
COMMENT ON COLUMN TB_DRIVE.D_NAME IS '드라이브명';
COMMENT ON COLUMN TB_DRIVE.D_CDATE IS '생성일';
COMMENT ON COLUMN TB_DRIVE.D_UDATE IS '수정일';
COMMENT ON COLUMN TB_DRIVE.D_PUB IS '공개여부';
COMMENT ON COLUMN TB_DRIVE.D_TRCAN IS '휴지통 여부';
COMMENT ON COLUMN TB_DRIVE.D_CRUID IS '생성자 고유번호';
COMMENT ON COLUMN TB_DRIVE.D_TID IS '팀 고유번호';


-- 6-2. 폴더 테이블
CREATE TABLE TB_DRIVE_FOLDER
(	
	FD_NO NUMBER NOT NULL, 
	FD_NAME VARCHAR2(50 BYTE), 
	FD_CDATE DATE, 
	FD_UDATE DATE, 
	FD_CRUID NUMBER NOT NULL, 
	FD_DID NUMBER NOT NULL, 
	FD_TID NUMBER NOT NULL, 
	CONSTRAINT TB_DRIVE_FOLDER_PK PRIMARY KEY (FD_NO, FD_DID, FD_TID), 
	CONSTRAINT TB_DRIVE_FOLDER_FK1 FOREIGN KEY (FD_TID, FD_DID) REFERENCES TB_DRIVE (D_TID, D_NO), 
	CONSTRAINT TB_DRIVE_FOLDER_FK2 FOREIGN KEY (FD_TID, FD_CRUID) REFERENCES TB_TEAM_USER (TU_TID, TU_MID)
);

COMMENT ON COLUMN TB_DRIVE_FOLDER.FD_NO IS '폴더 고유번호';
COMMENT ON COLUMN TB_DRIVE_FOLDER.FD_NAME IS '폴더명';
COMMENT ON COLUMN TB_DRIVE_FOLDER.FD_CDATE IS '생성일';
COMMENT ON COLUMN TB_DRIVE_FOLDER.FD_UDATE IS '수정일';
COMMENT ON COLUMN TB_DRIVE_FOLDER.FD_CRUID IS '생성자 고유번호';
COMMENT ON COLUMN TB_DRIVE_FOLDER.FD_DID IS '드라이브 고유번호';
COMMENT ON COLUMN TB_DRIVE_FOLDER.FD_TID IS '팀 고유번호';


-- 6-3. 파일 테이블
CREATE TABLE TB_DRIVE_FILE 
(	
	FL_NO NUMBER NOT NULL, 
	FL_NAME VARCHAR2(50 BYTE) NOT NULL, 
	FL_EXT CHAR(3 BYTE) NOT NULL, 
	FL_LOC VARCHAR2(100 BYTE) NOT NULL, 
	FL_SIZE NUMBER NOT NULL, 
	FL_CDATE DATE NOT NULL, 
	FL_UDATE DATE, 
	FL_CRUID NUMBER NOT NULL, 
	FL_FDID NUMBER NOT NULL, 
	FL_DID NUMBER NOT NULL, 
	FL_TID NUMBER NOT NULL, 
	CONSTRAINT TB_DRIVE_FILE_PK PRIMARY KEY (FL_NO, FL_DID, FL_TID), 
	CONSTRAINT TB_DRIVE_FILE_FK1 FOREIGN KEY (FL_TID, FL_DID) REFERENCES TB_DRIVE (D_TID, D_NO), 
	CONSTRAINT TB_DRIVE_FILE_FK2 FOREIGN KEY (FL_TID, FL_CRUID) REFERENCES TB_TEAM_USER (TU_TID, TU_MID), 
	CONSTRAINT TB_DRIVE_FILE_FK3 FOREIGN KEY (FL_FDID, FL_DID, FL_TID) REFERENCES TB_DRIVE_FOLDER (FD_NO, FD_DID, FD_TID)
);

COMMENT ON COLUMN TB_DRIVE_FILE.FL_NO IS '파일 고유번호';
COMMENT ON COLUMN TB_DRIVE_FILE.FL_NAME IS '파일명';
COMMENT ON COLUMN TB_DRIVE_FILE.FL_EXT IS '파일확장자명';
COMMENT ON COLUMN TB_DRIVE_FILE.FL_LOC IS '저장위치';
COMMENT ON COLUMN TB_DRIVE_FILE.FL_SIZE IS '파일크기';
COMMENT ON COLUMN TB_DRIVE_FILE.FL_CDATE IS '생성일';
COMMENT ON COLUMN TB_DRIVE_FILE.FL_UDATE IS '수정일';
COMMENT ON COLUMN TB_DRIVE_FILE.FL_CRUID IS '생성자 고유번호';
COMMENT ON COLUMN TB_DRIVE_FILE.FL_FDID IS '폴더 고유번호';
COMMENT ON COLUMN TB_DRIVE_FILE.FL_DID IS '드라이브 고유번호';
COMMENT ON COLUMN TB_DRIVE_FILE.FL_TID IS '팀 고유번호';



-- 7. 캘린더 테이블
  CREATE TABLE TB_CALENDER
   (   
   "CL_NO" NUMBER NOT NULL ENABLE, 
   "CL_DATE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   "CL_YEAR" NUMBER NOT NULL ENABLE, 
   "CL_MONTH" NUMBER NOT NULL ENABLE, 
   "CL_DAY" NUMBER NOT NULL ENABLE, 
   "CL_START" NUMBER, 
   "CL_END" NUMBER, 
   "CL_TITLE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
   "CL_CONTENT" VARCHAR2(2000 BYTE), 
   "CL_CDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
   "CL_UDATE" DATE, 
   "CL_CRUID" NUMBER NOT NULL ENABLE, 
   "CL_TID" NUMBER NOT NULL ENABLE, 
   CONSTRAINT "TB_CALENDER_PK" PRIMARY KEY ("CL_NO", "CL_TID")  ENABLE, 
   CONSTRAINT "TB_CALENDER_FK1" FOREIGN KEY ("CL_TID") REFERENCES "TB_TEAM" ("T_NO") ENABLE, 
   CONSTRAINT "TB_CALENDER_FK2" FOREIGN KEY ("CL_TID", "CL_CRUID") REFERENCES "TB_TEAM_USER" ("TU_TID", "TU_MID") ENABLE
   ) ;


COMMENT ON COLUMN TB_CALENDER.CL_NO IS '캘린더 고유번호';
COMMENT ON COLUMN TB_CALENDER.CL_DATE IS '캘린더 일자';
COMMENT ON COLUMN TB_CALENDER.CL_START IS '캘린더 시작시간';
COMMENT ON COLUMN TB_CALENDER.CL_END IS '캘린더 종료시간';
COMMENT ON COLUMN TB_CALENDER.CL_TITLE IS '캘린더 제목';
COMMENT ON COLUMN TB_CALENDER.CL_CONTENT IS '캘린더 내용';
COMMENT ON COLUMN TB_CALENDER.CL_CDATE IS '캘린더 등록일';
COMMENT ON COLUMN TB_CALENDER.CL_UDATE IS '캘린더 수정일';
COMMENT ON COLUMN TB_CALENDER.CL_CRUID IS '작성자 고유번호';
COMMENT ON COLUMN TB_CALENDER.CL_TID IS '팀 고유번호';



-- 8-2. 알람확인인원 테이블
CREATE TABLE TB_ALARM_CHECK 
(	
	AC_NO NUMBER NOT NULL, 
	AC_AID NUMBER NOT NULL, 
	AC_CDATE DATE NOT NULL, 
	AC_UID NUMBER NOT NULL, 
	AC_TID NUMBER NOT NULL
);

COMMENT ON COLUMN TB_ALARM_CHECK.AC_NO IS '고유번호';
COMMENT ON COLUMN TB_ALARM_CHECK.AC_AID IS '원알람 고유번호';
COMMENT ON COLUMN TB_ALARM_CHECK.AC_CDATE IS '알람 확인일자';
COMMENT ON COLUMN TB_ALARM_CHECK.AC_UID IS '회원 고유번호';
COMMENT ON COLUMN TB_ALARM_CHECK.AC_TID IS '팀 고유번호';


-- 9. 통합검색 테이블
CREATE TABLE TB_SEARCH 
(	
	S_NO NUMBER NOT NULL, 
	S_MENU VARCHAR2(20 BYTE) NOT NULL, 
	S_TITLE VARCHAR2(200 BYTE) NOT NULL, 
	S_CONTENT VARCHAR2(4000 BYTE), 
	S_DATE DATE NOT NULL, 
	S_CRUID NUMBER NOT NULL, 
	S_ID NUMBER NOT NULL, 
	S_TID NUMBER NOT NULL
);

COMMENT ON COLUMN TB_SEARCH.S_NO IS '고유번호';
COMMENT ON COLUMN TB_SEARCH.S_MENU IS '구분 게시물 카테고리/채팅/드라이브/캘린더';
COMMENT ON COLUMN TB_SEARCH.S_TITLE IS '제목 or 파일명';
COMMENT ON COLUMN TB_SEARCH.S_CONTENT IS '내용';
COMMENT ON COLUMN TB_SEARCH.S_DATE IS '등록일 or 수정일';
COMMENT ON COLUMN TB_SEARCH.S_CRUID IS '등록자 고유번호';
COMMENT ON COLUMN TB_SEARCH.S_ID IS '원 게시물의 고유번호';
COMMENT ON COLUMN TB_SEARCH.S_TID IS '팀 고유번호';


COMMIT;








